((root, factory) => {
  const Core = typeof module === "object" && module.exports ? require("./wave2-core.js") : root.MultiAgentWave2Core;
  const api = factory(Core);
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.MultiAgentWave2Db = api;
})(typeof globalThis !== "undefined" ? globalThis : this, (Core) => {
  "use strict";
  if (!Core) throw new Error("MultiAgentWave2Core is required");
  const DB_NAME="chatgpt_multi_orchestrator_wave1", DB_VERSION=2, LEASE_MS=120000, LEASE_RENEW_WINDOW_MS=30000;
  const STORE_NAMES=Object.freeze(["meta","runs","tasks","conversation_bindings","deliveries","leases","worker_results","events","upstream_events","faults"]);
  let dbPromise=null;
  const now=()=>Date.now();
  function makeId(prefix){if(globalThis.crypto?.randomUUID)return `${prefix}_${globalThis.crypto.randomUUID()}`;return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,12)}`;}
  function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error("IndexedDB request failed"));});}
  function txDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error||new Error("IndexedDB transaction aborted"));tx.onerror=()=>{};});}
  function ensureStore(db,r,name,options){return db.objectStoreNames.contains(name)?r.transaction.objectStore(name):db.createObjectStore(name,options);}function ensureIndex(s,name,key,options={}){if(!s.indexNames.contains(name))s.createIndex(name,key,options);}
  function openDb(){if(dbPromise)return dbPromise;if(!globalThis.indexedDB)return Promise.reject(new Error("IndexedDB is unavailable"));dbPromise=new Promise((resolve,reject)=>{const r=globalThis.indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;ensureStore(db,r,"meta",{keyPath:"key"});ensureStore(db,r,"runs",{keyPath:"run_id"});ensureStore(db,r,"tasks",{keyPath:"task_id"});const b=ensureStore(db,r,"conversation_bindings",{keyPath:"conversation_id"});ensureIndex(b,"provider_locator","provider_locator",{unique:true});const d=ensureStore(db,r,"deliveries",{keyPath:"delivery_id"});ensureIndex(d,"conversation_id","conversation_id",{unique:false});ensureIndex(d,"created_at","created_at",{unique:false});ensureIndex(d,"task_id","task_id",{unique:false});ensureStore(db,r,"leases",{keyPath:"conversation_id"});const wr=ensureStore(db,r,"worker_results",{keyPath:"delivery_id"});ensureIndex(wr,"task_id","task_id",{unique:false});const e=ensureStore(db,r,"events",{keyPath:"seq"});ensureIndex(e,"delivery_id","delivery_id",{unique:false});ensureIndex(e,"conversation_id","conversation_id",{unique:false});ensureIndex(e,"task_id","task_id",{unique:false});const u=ensureStore(db,r,"upstream_events",{keyPath:"event_id"});ensureIndex(u,"task_id","task_id",{unique:false});ensureIndex(u,"dedupe_key","dedupe_key",{unique:true});const faults=ensureStore(db,r,"faults",{keyPath:"fault_id"});ensureIndex(faults,"delivery_id","delivery_id",{unique:false});ensureIndex(faults,"point","point",{unique:false});};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{dbPromise=null;reject(r.error||new Error("Could not open Wave-2 IndexedDB"));};r.onblocked=()=>reject(new Error("Wave-2 IndexedDB upgrade is blocked"));});return dbPromise;}
  async function withTx(names,mode,fn){const db=await openDb(),tx=db.transaction([...new Set(names)],mode),done=txDone(tx);try{const out=await fn(tx);await done;return out;}catch(error){try{tx.abort();}catch{}await done.catch(()=>{});throw error;}}
  const os=(tx,name)=>tx.objectStore(name);
  function compactEvidence(v){const out={};if(!v||typeof v!=="object")return out;for(const[k,x]of Object.entries(v)){if(x==null)continue;out[k]=typeof x==="boolean"||typeof x==="number"?x:String(x).slice(0,240);}return out;}
  async function appendEvent(tx,input){const meta=os(tx,"meta"),events=os(tx,"events"),cur=await req(meta.get("journal_seq")),seq=Math.max(0,Number(cur?.value)||0)+1;meta.put({key:"journal_seq",value:seq});const d=input.delivery||{};const ev={seq,timestamp:Number(input.timestamp)||now(),event_type:String(input.event_type||"STATE_TRANSITION"),run_id:String(d.run_id||input.run_id||""),task_id:String(d.task_id||input.task_id||""),delivery_id:String(d.delivery_id||input.delivery_id||""),conversation_id:String(d.conversation_id||input.conversation_id||""),logical_agent_id:String(d.logical_agent_id||input.logical_agent_id||""),slot_id:String(d.slot_id||input.slot_id||""),previous_state:input.previous_state==null?null:String(input.previous_state),next_state:input.next_state==null?null:String(input.next_state),reason:String(input.reason||"").slice(0,240),lease_fence:Math.max(0,Number(input.lease_fence??d.lease_fence)||0),actor_id:String(input.actor_id||d.actor_id||"").slice(0,220),boot_id:String(input.boot_id||"").slice(0,220),evidence:compactEvidence(input.evidence)};events.add(ev);return ev;}
  async function readDelivery(tx,id){const d=await req(os(tx,"deliveries").get(String(id||"")));if(!d)throw new Error("Wave-2 Delivery was not found");return d;}
  function transition(d,next,at=now()){if(d.state===next)return d;if(!Core.canTransition(d.state,next))throw new Error(`Invalid Wave-2 Delivery transition ${d.state} -> ${next}`);return {...d,state:next,updated_at:at};}
  async function assertFence(tx,d,actor,fence,{fresh=true,at=now()}={}){const l=await req(os(tx,"leases").get(d.conversation_id));if(!l||String(l.owner_actor_id)!==String(actor||"")||Number(l.fence)!==Number(fence)||Number(d.lease_fence)!==Number(fence)){const e=new Error("Wave-2 sender lease fence is stale");e.code="wave2.lease_stale";throw e;}if(fresh&&Number(l.expires_at)<=at){const e=new Error("Wave-2 sender lease expired");e.code="wave2.lease_expired";throw e;}return l;}
  return Object.freeze({Core,DB_NAME,DB_VERSION,LEASE_MS,LEASE_RENEW_WINDOW_MS,STORE_NAMES,now,makeId,req,openDb,withTx,os,compactEvidence,appendEvent,readDelivery,transition,assertFence});
});
