const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const read=n=>fs.readFileSync(path.join(__dirname,'..',n),'utf8');

test('Wave 2 uses DB v2 migration stores and durable startup enumeration',()=>{const s=read('wave2-db.js'),w1=read('wave1-store.js'),b=read('wave2-background.js');assert.match(s,/DB_VERSION=3/);assert.match(s,/"upstream_events","faults"/);assert.match(w1,/const DB_VERSION = 3/);assert.match(w1,/upstream_events/);assert.match(w1,/faults/);assert.match(b,/await Store\.openDb\(\)/);assert.match(b,/await Store\.listNonterminalDeliveries\(\)/);assert.ok(b.indexOf('await Store.openDb()')<b.indexOf('chrome.tabs.query'));});
test('consumed SUBMITTING capability blocks fence transfer until permit expiry',()=>{const s=read('wave2-delivery-store.js');const start=s.indexOf('async function acquireLease');const end=s.indexOf('async function transitionWithFence',start);const x=s.slice(start,end);assert.match(x,/d\.state==="SUBMITTING"&&d\.send_consumed_at/);assert.match(x,/wave2\.lease_handoff_deferred/);assert.ok(x.indexOf('lease_handoff_deferred')<x.indexOf('const fence='));});
test('continuation and repair children are parent-deduplicated and have new Delivery IDs',()=>{const s=read('wave2-delivery-store.js');const start=s.indexOf('async function createChildDelivery');const end=s.indexOf('async function acquireLease',start);const x=s.slice(start,end);assert.match(x,/causal_parent_delivery_id===parent\.delivery_id&&d\.kind===kind/);assert.match(x,/makeId\("delivery"\)/);assert.match(x,/conversation_seq/);assert.match(x,/CONTINUATION_CREATED/);assert.match(x,/PROTOCOL_REPAIR_CREATED/);});
test('result persistence and acknowledgement are separate durable boundaries',()=>{const s=read('wave2-result-store.js'),b=read('wave2-background.js');assert.match(s,/async function persistWorkerResult/);assert.match(s,/async function ackPersistedResult/);assert.match(b,/Store\.persistWorkerResult/);assert.match(b,/after_result_persist/);assert.match(b,/Store\.ackPersistedResult/);const p0=b.indexOf('const persisted=await Store.persistWorkerResult');const p1=b.indexOf('after_result_persist',p0);const p2=b.indexOf('Store.ackPersistedResult',p1);assert.ok(p0>=0&&p1>p0&&p2>p1);});
test('production Send remains one-shot Wave-1 actuator and Wave-2 never adds a second low-level path',()=>{const c=read('wave2-content.js');assert.equal((c.match(/Dom\.invokeAuthorizedSend/g)||[]).length,1);assert.doesNotMatch(c,/submitComposer\(|\.click\(\)|requestSubmit\(/);assert.match(c,/d\.state==="SUBMITTING"&&!d\.send_consumed_at/);});
test('manual interference has explicit pause and explicit resume',()=>{const s=read('wave2-result-store.js'),b=read('wave2-background.js');assert.match(s,/async function pauseManual/);assert.match(s,/async function resumeManual/);assert.match(s,/paused=true/);assert.match(b,/WAVE2_PAUSE_MANUAL/);assert.match(b,/WAVE2_RESUME_MANUAL/);assert.match(b,/RESPONSE_RECEIVED/);});
test('all required deterministic fault points are represented and X007 X008 trigger real reload paths',()=>{const f=read('wave2-faults.js'),b=read('wave2-background.js'),c=read('wave2-content.js');for(const p of ['after_delivery_persist','after_composer_write','after_submitting_commit','after_send_invocation','after_user_receipt','after_response_detected','after_result_persist','service_worker_restart','tab_reload_during_generation','duplicate_observer_callbacks','drop_observer_callbacks','connection_interruption','retry_error_state'])assert.match(f,new RegExp(p));assert.match(b,/service_worker_restart/);assert.match(b,/chrome\?\.runtime\?\.reload|chrome\.runtime\.reload/);assert.match(c,/tab_reload_during_generation/);assert.match(c,/location\?\.reload|location\.reload/);assert.match(c,/MultiAgentWave2Dev/);assert.match(f,/runtime\\?\\.reload|runtime\\.reload/);assert.match(c,/crashIfFault/);assert.match(c,/location\\?\\.reload|location\\.reload/);});
test('unknown delivery has no automated retry transition',()=>{const c=read('wave2-core.js');assert.match(c,/DELIVERY_UNKNOWN: new Set\(\)/);assert.doesNotMatch(c,/DELIVERY_UNKNOWN:\s*new Set\(\["PENDING"/);});
test('runtime packaging loads Wave 2 service-worker and content modules',()=>{const w=read('background-wrapper.js'),m=JSON.parse(read('manifest.json')),p=read('scripts/package.mjs'),t=read('tab-supervisor.js');for(const x of ['wave2-core.js','wave2-db.js','wave2-delivery-store.js','wave2-result-store.js','wave2-store.js','wave2-faults.js','wave2-background.js'])assert.match(w,new RegExp(x.replace('.','\\.')));for(const x of ['wave2-core.js','wave2-dom.js','wave2-content.js'])assert.ok(m.content_scripts[0].js.includes(x));assert.match(p,/wave2-background\.js/);assert.match(p,/wave2-content\.js/);assert.match(t,/WAVE2_CONTENT_HEALTH/);});
