const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const read=n=>fs.readFileSync(path.join(__dirname,'..',n),'utf8');

test('Wave 2 uses DB v3 migration stores and durable startup enumeration',()=>{const s=read('wave2-db.js'),w1=read('wave1-store.js'),b=read('wave2-background.js');assert.match(s,/DB_VERSION=3/);assert.match(s,/"upstream_events","faults"/);assert.match(w1,/const DB_VERSION = 3/);assert.match(w1,/upstream_events/);assert.match(w1,/faults/);assert.match(b,/await Store\.openDb\(\)/);assert.match(b,/await Store\.listNonterminalDeliveries\(\)/);const startup=b.slice(b.indexOf('async function startupReconcile'),b.indexOf('startupReconcile().catch'));assert.ok(startup.indexOf('await Store.openDb()')>=0&&startup.indexOf('await Store.openDb()')<startup.indexOf('await queryTabs('));});
test('consumed SUBMITTING capability blocks fence transfer until permit expiry',()=>{const s=read('wave2-delivery-store.js');const start=s.indexOf('async function acquireLease');const end=s.indexOf('async function transitionWithFence',start);const x=s.slice(start,end);assert.match(x,/d\.state==="SUBMITTING"&&d\.send_consumed_at/);assert.match(x,/wave2\.lease_handoff_deferred/);assert.ok(x.indexOf('lease_handoff_deferred')<x.indexOf('const fence='));});
test('continuation and repair children are parent-deduplicated and have new Delivery IDs',()=>{const s=read('wave2-delivery-store.js');const start=s.indexOf('async function createChildDelivery');const end=s.indexOf('async function acquireLease',start);const x=s.slice(start,end);assert.match(x,/causal_parent_delivery_id===parent\.delivery_id&&d\.kind===kind/);assert.match(x,/makeId\("delivery"\)/);assert.match(x,/conversation_seq/);assert.match(x,/CONTINUATION_CREATED/);assert.match(x,/PROTOCOL_REPAIR_CREATED/);});
test('result persistence and acknowledgement are separate durable boundaries',()=>{const s=read('wave2-result-store.js'),b=read('wave2-background.js');assert.match(s,/async function persistWorkerResult/);assert.match(s,/async function ackPersistedResult/);assert.match(b,/Store\.persistWorkerResult/);assert.match(b,/after_result_persist/);assert.match(b,/Store\.ackPersistedResult/);const p0=b.indexOf('const persisted=await Store.persistWorkerResult');const p1=b.indexOf('after_result_persist',p0);const p2=b.indexOf('Store.ackPersistedResult',p1);assert.ok(p0>=0&&p1>p0&&p2>p1);});
test('production Send remains one-shot and recovered SUBMITTING reconciles before re-entry',()=>{const c=read('wave2-content.js');assert.equal((c.match(/Dom\.invokeAuthorizedSend/g)||[]).length,1);assert.doesNotMatch(c,/submitComposer\(|\.click\(\)|requestSubmit\(/);const recover=c.slice(c.indexOf('async function recoverDelivery'),c.indexOf('async function reconcileNow'));assert.doesNotMatch(recover,/SUBMITTING/);assert.match(c,/r\.positive_non_delivery&&d\?\.state==="SUBMITTING"&&!d\.send_consumed_at/);});
test('manual interference has explicit pause and explicit resume',()=>{const s=read('wave2-result-store.js'),b=read('wave2-background.js');assert.match(s,/async function pauseManual/);assert.match(s,/async function resumeManual/);assert.match(s,/paused=true/);assert.match(b,/WAVE2_PAUSE_MANUAL/);assert.match(b,/WAVE2_RESUME_MANUAL/);assert.match(b,/RESPONSE_RECEIVED/);});
test('all required deterministic fault points are represented and X007 X008 trigger real reload paths',()=>{const f=read('wave2-faults.js'),b=read('wave2-background.js'),c=read('wave2-content.js');for(const p of ['after_delivery_persist','after_composer_write','after_submitting_commit','after_send_invocation','after_user_receipt','after_response_detected','after_result_persist','service_worker_restart','tab_reload_during_generation','duplicate_observer_callbacks','drop_observer_callbacks','connection_interruption','retry_error_state'])assert.match(f,new RegExp(p));assert.match(f,/runtime\?\.reload|runtime\.reload/);assert.match(b,/service_worker_restart/);assert.match(b,/runtime\?\.reload|runtime\.reload/);assert.match(c,/tab_reload_during_generation/);assert.match(c,/base\.generating/);assert.match(c,/location\?\.reload|location\.reload/);assert.match(c,/MultiAgentWave2Dev/);});
test('unknown delivery has no automated retry transition',()=>{const c=read('wave2-core.js');assert.match(c,/DELIVERY_UNKNOWN: new Set\(\)/);assert.doesNotMatch(c,/DELIVERY_UNKNOWN:\s*new Set\(\["PENDING"/);});
test('runtime packaging loads Wave 2 service-worker and content modules',()=>{const w=read('background-wrapper.js'),m=JSON.parse(read('manifest.json')),p=read('scripts/package.mjs'),t=read('tab-supervisor.js');for(const x of ['wave2-core.js','wave2-db.js','wave2-delivery-store.js','wave2-result-store.js','wave2-store.js','wave2-faults.js','wave2-background.js'])assert.match(w,new RegExp(x.replace('.','\\.')));for(const x of ['wave2-core.js','wave2-dom.js','wave2-content.js'])assert.ok(m.content_scripts[0].js.includes(x));assert.match(p,/wave2-background\.js/);assert.match(p,/wave2-content\.js/);assert.match(t,/WAVE2_CONTENT_HEALTH/);});

test('protocol repair closes malformed parent as RESPONSE_SUPERSEDED while retaining response evidence',()=>{const c=read('wave2-core.js'),d=read('wave2-delivery-store.js');assert.match(c,/RESPONSE_RECEIVED: new Set\(\["ACKED", "RESPONSE_SUPERSEDED"\]\)/);assert.match(d,/PROTOCOL_REPAIR_PARENT_CLOSED/);assert.match(d,/transition\(parent,"RESPONSE_SUPERSEDED"/);assert.match(d,/response_text_hash/);});
test('hard pre-send budget exhaustion fails before side effects and persists controller escalation',()=>{const b=read('wave2-background.js');const a=b.slice(b.indexOf('async function handleAcquire'),b.indexOf('async function handleBeginFill'));assert.match(a,/Core\.budgetDecision/);assert.match(a,/Core\.PRE_SEND_STATES/);assert.match(a,/Store\.failPreSend/);assert.match(a,/Store\.emitBudgetEscalation/);});
test('rate-limited and user-required UI are blocking lane states',()=>{const c=read('wave2-core.js'),b=read('wave2-background.js');assert.match(c,/USER_REQUIRED/);assert.match(c,/RATE_LIMITED/);assert.match(b,/ui==="USER_REQUIRED"/);assert.match(b,/ui==="RATE_LIMITED"/);});

test('deferred consumed-permit handoff schedules safe recovery retry instead of stalling',()=>{const c=read('wave2-content.js');const start=c.indexOf('async function recoverDelivery');const end=c.indexOf('async function reconcileNow',start);const x=c.slice(start,end);assert.match(x,/wave2\.lease_handoff_deferred/);assert.match(x,/retry_at/);assert.match(x,/setTimeout\(\(\)=>recoverDelivery\(deliveryId\)/);});


test('startup reconciliation is a read-only barrier before Wave-2 side effects',()=>{const b=read('wave2-background.js'),c=read('wave2-content.js');assert.match(b,/let recoveryReady=false/);assert.match(b,/RECOVERY_GATED_TYPES/);assert.match(b,/requireRecoveryReady\(m\.type\)/);assert.match(b,/WAVE2_READONLY_SNAPSHOT/);assert.match(b,/RESTART_RECONCILIATION_DECISION/);assert.match(b,/Core\.classifyReconciliation\(d,observation\)/);assert.match(b,/STARTUP_RECONCILIATION_READY/);const startup=b.slice(b.indexOf('async function startupReconcile'),b.indexOf('startupReconcile().catch'));assert.ok(startup.indexOf('WAVE2_READONLY_SNAPSHOT')>=0&&startup.indexOf('WAVE2_READONLY_SNAPSHOT')<startup.indexOf('Core.classifyReconciliation(d,observation)'));assert.ok(startup.indexOf('Core.classifyReconciliation(d,observation)')<startup.indexOf('recoveryReady=true'));assert.match(c,/WAVE2_READONLY_SNAPSHOT/);assert.match(c,/wave2\.recovery_not_ready/);});
test('controller budget escalation is sticky and result recovery is Delivery-keyed',()=>{const s=read('wave2-result-store.js'),b=read('wave2-background.js');assert.match(s,/controller_escalation\?\.reason==="BUDGET_EXHAUSTED"/);assert.match(s,/controller_budget:\$\{task_id\}/);assert.match(s,/async function getWorkerResult/);assert.match(b,/Store\.getWorkerResult\(d\.delivery_id\)/);assert.doesNotMatch(b,/getStatusByLocator\(d\.provider_locator\)\)\.result/);});
test('configured protocol repair budget may issue another bounded repair before exhaustion',()=>{const b=read('wave2-background.js');const start=b.indexOf('if(!parsed.ok)');const x=b.slice(start,b.indexOf('const persisted=',start));assert.doesNotMatch(x,/d\.kind==="PROTOCOL_REPAIR"/);assert.match(x,/protocol_repair_attempts/);});
