const test=require('node:test');
const assert=require('node:assert/strict');
const Core=require('../wave2-core.js');
const ctx={run_id:'run_1',task_id:'task_1',logical_agent_id:'agent_1',slot_id:'slot_1',conversation_id:'conversation_1',delivery_id:'delivery_1',conversation_seq:1,ownership_token:'own_1'};
function block(status,extra={}){return ['prose',Core.WORKER_START,JSON.stringify({...Core.currentContext(ctx),status,...extra}),Core.WORKER_END].join('\n');}
test('universal payload supports assignment continuation and repair kinds',()=>{for(const kind of ['ASSIGNMENT','CONTINUATION','PROTOCOL_REPAIR']){const p=Core.buildRouterPayload({...ctx,kind,instruction:'Do work.'});assert.match(p,new RegExp(`kind: ${kind}`));assert.match(p,/delivery_1/);}});
test('parser accepts CONTINUE DONE and structured ESCALATE only',()=>{assert.equal(Core.parseWorkerTerminal(block('CONTINUE'),ctx).ok,true);assert.equal(Core.parseWorkerTerminal(block('DONE'),ctx).ok,true);assert.equal(Core.parseWorkerTerminal(block('ESCALATE',{reason:'NEEDS_USER'}),ctx).ok,true);assert.equal(Core.parseWorkerTerminal(block('ESCALATE',{reason:'MADE_UP'}),ctx).ok,false);assert.equal(Core.parseWorkerTerminal(block('DONE',{reason:'NEEDS_USER'}),ctx).ok,false);});
test('continuation and repair prompts are minimal and do not rerun work',()=>{assert.equal(Core.continuationInstruction('task_1'),'Continue task task_1 from your current state. Do not restart. Do not merely summarize prior work. Return the normal terminal worker block when this turn ends.');const r=Core.protocolRepairInstruction(ctx);assert.match(r,/only the corrected terminal/);assert.match(r,/Do not repeat, restart, extend/);assert.match(r,/do not reuse identifiers from the prior turn/);});
test('DELIVERY_UNKNOWN and terminal states have no outgoing transitions',()=>{assert.equal(Core.canTransition('DELIVERY_UNKNOWN','PENDING'),false);assert.equal(Core.canTransition('ACKED','PENDING'),false);});
test('hard budget boundaries exhaust exactly at configured limit',()=>{const base={created_at:1000,started_at:1000,max_continuations:3,max_recoverable_failures:2,max_elapsed_ms:5000,continuation_count:2,recoverable_failure_count:1};assert.equal(Core.budgetDecision(base,5999).ok,true);assert.deepEqual(Core.budgetDecision({...base,continuation_count:3},2000),{ok:false,reason:'BUDGET_EXHAUSTED',dimension:'continuations'});assert.deepEqual(Core.budgetDecision({...base,recoverable_failure_count:2},2000),{ok:false,reason:'BUDGET_EXHAUSTED',dimension:'recoverable_failures'});assert.deepEqual(Core.budgetDecision(base,6000),{ok:false,reason:'BUDGET_EXHAUSTED',dimension:'elapsed'});});
test('UI normalization distinguishes thinking errors connection auth rate and unknown',()=>{assert.equal(Core.normalizeUiState({generating:true,thinking:true,composer_present:true,idle_send_path:false}),'LONG_THINKING');assert.equal(Core.normalizeUiState({error_code:'retryable_model_error',composer_present:true,idle_send_path:true}),'RETRYABLE_MODEL_ERROR');assert.equal(Core.normalizeUiState({error_code:'connection_waiting',composer_present:true,idle_send_path:true}),'CONNECTION_WAITING');assert.equal(Core.normalizeUiState({error_code:'auth_required'}),'AUTHENTICATION_REQUIRED');assert.equal(Core.normalizeUiState({error_code:'rate_limited'}),'RATE_LIMITED');assert.equal(Core.normalizeUiState({composer_present:false,generating:false}),'UNRECOGNIZED_UI');});
test('reconciliation never resends consumed SUBMITTING delivery',()=>{assert.deepEqual(Core.classifyReconciliation({state:'SUBMITTING',send_consumed_at:123},{composer_empty:true}),{action:'DELIVERY_UNKNOWN'});assert.deepEqual(Core.classifyReconciliation({state:'SUBMITTING',send_consumed_at:0},{positive_non_delivery:true}),{action:'RECOVER_PRE_SEND'});});
